Fix startup and exit from application
After adding the __name__ == '__main__' boilerplate code, I got this
error:
    NameError: name 'config_path' is not defined

I also replaced all calls to `exit()` with `sys.exit()` since the former
is meant for the interactive interpreter.